services:
  server:
    container_name: ${CONTAINER_NAME}
    build:
      context: ./hoseruFront
      dockerfile: Dockerfile
    volumes:
      - ./hoseruFront:/app
      - /app/node_modules  # ホスト側のnode_modulesで上書きしないように
    ports:
      - "${FRONTEND_PORT}:3000"
    tty: true
    # command: >
    #   /bin/sh -c '
    #   npx create-react-app@latest --ts
    #   '
